version: '3'
services:
  nginx:
    image: place-nginx
    container_name: place-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - stac-api
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
    ports:
      - 8080:80
  stac:
    container_name: place-stac-server
    image: place-stac-server
    build:
      context: .
      dockerfile: place/stac/Dockerfile
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - TILER_ROOT=http://localhost:8000
      - RELOAD=true
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
    ports:
      - "8081:8081"
    networks:
      - stac-api
    volumes:
      - ./place:/app/place
      - ./scripts:/app/scripts
    depends_on:
      - database
    command:
      bash -c "./scripts/wait-for-it.sh database:5432 && python -m place.stac.app"
  tiler:
    container_name: place-stac-tiler
    platform: linux/amd64
    build:
      context: .
      dockerfile: place/tiles/Dockerfile
    environment:
      # pg connection
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      # Application
      - HOST=0.0.0.0
      - PORT=8082
      # Uvicorn
      # http://www.uvicorn.org/settings/#production
      - WEB_CONCURRENCY=4
      # GDAL config
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - AWS_NO_SIGN_REQUEST=TRUE
      - AWS_S3_ENDPOINT=s3.af-south-1.amazonaws.com
      - AWS_REGION=af-south-1
    ports:
      - "8082:8082"
    networks:
      - stac-api
    depends_on:
      - database
    volumes:
      - ./place:/app/place
    command:
      bash -c "./scripts/wait-for-it.sh database:5432 && python -m place.tiles.app"
  database:
    container_name: place-stac-db
    image: ghcr.io/stac-utils/pgstac:v0.7.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    networks:
      - stac-api
    command: postgres -N 500
  load-place:
    image: place-stac-server
    environment:
      - ENVIRONMENT=development
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=postgis
    depends_on:
      - database
      - stac
    networks:
      - stac-api
    volumes:
      - ./place:/app/place
      - ./scripts:/app/scripts
    command:
      - "./scripts/wait-for-it.sh"
      - "database:5432"
      - "--"
      - "python"
      - "/app/scripts/ingest_place.py"
      - "database:5432"

networks:
  stac-api: