site_name: stac-fastapi
site_description: STAC FastAPI.

# Repository
repo_name: 'stac-utils/stac-fastapi'
repo_url: 'https://github.com/stac-utils/stac-fastapi'
edit_uri: 'blob/master/docs/src/'


# Social links
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/stac-utils'

# Layout
nav:
  - Home: 'index.md'
  - API:
    - stac_fastapi.api:
      - app: api/stac_fastapi/api/app.md
      - config: api/stac_fastapi/api/config.md
      - errors: api/stac_fastapi/api/errors.md
      - middleware: api/stac_fastapi/api/middleware.md
      - models: api/stac_fastapi/api/models.md
      - openapi: api/stac_fastapi/api/openapi.md
      - routes: api/stac_fastapi/api/routes.md
    - stac_fastapi.extensions:
      - core:
          - context: api/stac_fastapi/extensions/core/context.md
          - filter: api/stac_fastapi/extensions/core/filter/filter.md
          - fields: api/stac_fastapi/extensions/core/fields/fields.md
          - query: api/stac_fastapi/extensions/core/query/query.md
          - sort: api/stac_fastapi/extensions/core/sort/sort.md
          - transaction: api/stac_fastapi/extensions/core/transaction.md
          - pagination: api/stac_fastapi/extensions/core/pagination/pagination.md
      - third_party:
          - bulk_transactions: api/stac_fastapi/extensions/third_party/bulk_transactions.md
    - stac_fastapi.server:
      - app: api/stac_fastapi/server/app.md
    - stac_fastapi.types:
      - core: api/stac_fastapi/types/core.md
      - config: api/stac_fastapi/types/config.md
      - errors: api/stac_fastapi/types/errors.md
      - extension: api/stac_fastapi/types/extension.md
      - index: api/stac_fastapi/types/index.md
      - search: api/stac_fastapi/types/search.md
      - version: api/stac_fastapi/types/version.md
  - Development - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

plugins:
  - search

# Theme
theme:
  icon:
    logo: 'material/home'
    repo: 'fontawesome/brands/github'
  name: 'material'
  language: 'en'
  font:
    text: 'Nunito Sans'
    code: 'Fira Code'

extra_css:
  - stylesheets/extra.css

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
